import os
import re

def refine_pages():
    input_file = 'api-list.txt'
    pages_dir = 'pages'
    
    # Smart Display Function Code to be injected
    smart_display_code = """
def smart_display(data):
    # 1. Handle Lists
    if isinstance(data, list):
        if len(data) > 0 and isinstance(data[0], dict):
            st.dataframe(data)
            # Also check first item for image
            first_item = data[0]
            for k, v in first_item.items():
                if isinstance(v, str) and (v.endswith('.jpg') or v.endswith('.png') or v.endswith('.gif') or v.startswith('http')):
                    if 'image' in k.lower() or 'img' in k.lower() or 'url' in k.lower() or 'src' in k.lower():
                        st.image([item.get(k) for item in data[:5] if item.get(k)], width=200)
                        break
        else:
            st.write(data)
        return

    # 2. Handle Dictionaries
    if isinstance(data, dict):
        # Check for Images
        for k, v in data.items():
            if isinstance(v, str) and (v.endswith('.jpg') or v.endswith('.png') or v.endswith('.gif')):
                st.image(v, caption=k)
                return
            # Check for common image keys even if extension is missing (sometimes)
            if 'image' in k.lower() and isinstance(v, str) and v.startswith('http'):
                st.image(v, caption=k)
                return
        
        # Check for Quotes/Facts/Text
        for k, v in data.items():
            if k.lower() in ['quote', 'fact', 'joke', 'text', 'setup', 'delivery', 'advice']:
                st.info(f"**{k.capitalize()}:** {v}")
                # Don't return, might have more info
        
        # Check for nested data
        for k, v in data.items():
            if isinstance(v, (dict, list)):
                with st.expander(f"{k} Details"):
                    smart_display(v)
                    
        # Display simple key-values
        for k, v in data.items():
            if isinstance(v, (str, int, float, bool)) and k.lower() not in ['quote', 'fact', 'joke', 'text', 'setup', 'delivery', 'advice']:
                 # Filter out image urls we already showed
                 if isinstance(v, str) and v.startswith('http') and ('image' in k.lower() or 'img' in k.lower()):
                     continue
                 st.write(f"**{k}:** {v}")
"""

    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            
        page_number = 81
        
        # Regex to parse the line
        line_pattern = re.compile(r'\|\s*\[(.*?)\]\((.*?)\)\s*\|\s*(.*?)\s*\|')
        
        for line in lines:
            match = line_pattern.search(line)
            if match:
                api_name = match.group(1).strip()
                api_url = match.group(2).strip()
                api_desc = match.group(3).strip()
                
                # Sanitize name for filename
                safe_name = "".join([c if c.isalnum() or c == ' ' else '' for c in api_name])
                safe_name = safe_name.replace(' ', '_')
                
                filename = f"{page_number}_🌐_{safe_name}.py"
                filepath = os.path.join(pages_dir, filename)
                
                print(f"Checking {filepath}...")
                # Only update if file exists (meaning it was generated by us)
                if os.path.exists(filepath):
                    
                    # Determine a hint for the user based on description
                    type_hint = "Generic"
                    if any(x in api_desc.lower() for x in ['image', 'photo', 'picture', 'gif']):
                        type_hint = "Image"
                    elif any(x in api_desc.lower() for x in ['quote', 'fact', 'joke', 'text']):
                        type_hint = "Text"
                    elif any(x in api_desc.lower() for x in ['weather', 'crypto', 'price', 'data']):
                        type_hint = "Data"

                    # Construct content carefully to avoid f-string issues with triple quotes
                    content = f'''import streamlit as st
import requests

st.set_page_config(page_title="{api_name}", page_icon="🌐")

st.title("🌐 {api_name}")
st.markdown("""
{api_desc}

**URL:** [{api_url}]({api_url})
""")

# Smart Display Logic
{smart_display_code}

st.subheader("Live Demo")
url = st.text_input("API Endpoint", "{api_url}")

if st.button("Fetch Data"):
    try:
        with st.spinner("Fetching data..."):
            response = requests.get(url, timeout=5)
        
        st.write(f"**Status:** {{response.status_code}}")
        
        if response.status_code == 200:
            try:
                data = response.json()
                
                # Use Smart Display
                st.success("Data fetched successfully!")
                smart_display(data)
                
                with st.expander("View Raw JSON"):
                    st.json(data)
                    
            except ValueError:
                st.warning("Response is not JSON. Displaying as text:")
                st.text(response.text[:1000])
        else:
            st.error("Failed to fetch data.")
            
    except Exception as e:
        st.error(f"An error occurred: {{e}}")
'''
                    with open(filepath, 'w', encoding='utf-8') as f_out:
                        f_out.write(content)
                    
                    print(f"Refined {filename} ({type_hint})")
                
                page_number += 1
                
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    refine_pages()
